language: cpp
os: linux
dist: bionic
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
  - ctest --output-on-failure
jobs:
  include:
    - name: Linux GCC
      compiler: gcc
    - name: Windows MSVC
      os: windows
      script:
        - mkdir build
        - cd build
        - cmake -G "Visual Studio 15 2017 Win64" ..
        - cmake --build . --config Release
        - ctest -C Release --output-on-failure
    - name: macOS Clang
      os: osx        
      compiler: clang
    - name: Linux Clang
      compiler: clang
    - name: Windows Clang
      os: windows
      install: choco install ninja
      script: ./library/tools/travis-windows-clang.bat
    - name: Linux GCC (checker)
      compiler: gcc
      cache: ccache
      env: CC="ccache gcc" CXX="ccache g++"
      script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - cmake --build .
        - ctest --output-on-failure
        - cd ../checker
        - ./checkout.sh
        - ./build.sh
    - name: Windows MSVC (checker)
      os: windows
      script:
        - mkdir build
        - cd build
        - cmake -G "Visual Studio 15 2017 Win64" ..
        - cmake --build . --config Release
        - ctest -C Release --output-on-failure
        - cd ../checker
        - #./checkout.bat
        - #./build.bat
  allow_failures:        
    - name: macOS Clang
    - name: Windows Clang
    - name: Linux GCC (checker)
    - name: Windows MSVC (checker)
