language: cpp
os: linux
dist: bionic
notifications:
  email:
    if: branch = master OR branch = develop
script:
  - cd library
  - ./checkout-eastl.sh
  - ./src/iibmalloc/src/foundation/tools/travis-unix.sh
addons:
  apt:
    packages:
      - ninja-build
jobs:
  include:
    - name: Linux GCC
      compiler: gcc
    - name: Windows MSVC
      os: windows
      script:
        - cd library
        - ./checkout-eastl.bat
        - ./src/iibmalloc/src/foundation/tools/travis-windows-msvc.bat
    - name: macOS Clang
      os: osx        
      compiler: clang
    - name: Linux Clang
      compiler: clang
    - name: Windows Clang
      os: windows
      install: choco install ninja
      script:
        - cd library
        - ./checkout-eastl.bat
        - ./src/iibmalloc/src/foundation/tools/travis-windows-clang.bat
  allow_failures:        
    - name: macOS Clang
    - name: Windows Clang
