language: cpp
os: linux
dist: bionic
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
  - ctest --output-on-failure
jobs:
  include:
    - name: Linux GCC
      compiler: gcc
    - name: Windows MSVC
      os: windows
      script:
        - mkdir build
        - cd build
        - cmake -G "Visual Studio 15 2017 Win64" ..
        - cmake --build . --config Release
        - ctest -C Release --output-on-failure
    - name: macOS Clang
      os: osx        
      compiler: clang
    - name: Linux Clang
      compiler: clang
    - name: Windows Clang
      os: windows
      install: choco install ninja
      script: ./library/src/iibmalloc/src/foundation/tools/travis-windows-clang.bat
    - name: Linux GCC (checker)
      compiler: gcc
      cache: ccache
      script: ./checker/tools/travis-ccache.sh
    - name: macOS Clang (checker)
      os: osx        
      compiler: clang
      install: brew install ccache
      script: ./checker/tools/travis-ccache.sh
  allow_failures:        
    - name: macOS Clang
    - name: Windows Clang
    - name: Linux GCC (checker)
    - name: macOS Clang (checker)
