language: cpp
os: linux
dist: bionic
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
  - ctest
jobs:
  include:
    - name: Linux Clang
      compiler: clang
    - name: Linux GCC
      compiler: gcc
    - name: Windows MSVC
      os: windows
      script: ./library/tools/travis-windows-msvc2017.bat
    - name: Windows Clang
      os: windows
      install: choco install ninja
      script: ./library/tools/travis-windows-clang.bat
    - name: macOS Clang
      os: osx
  allow_failures:        
    - name: macOS Clang
    - name: Windows Clang
