language: cpp
os: linux
dist: bionic
notifications:
  email:
    if: branch = master OR branch = develop
script:
  - cd library
  - ./checkout-eastl.sh
  - ./src/iibmalloc/src/foundation/tools/travis-unix.sh
addons:
  apt:
    packages:
      - ninja-build
jobs:
  include:
    - name: Linux GCC
      compiler: gcc
    - name: Windows MSVC
      os: windows
      script:
        - cd library
        - ./checkout-eastl.bat
        - ./src/iibmalloc/src/foundation/tools/travis-windows-msvc.bat
    - name: macOS Clang
      os: osx        
      compiler: clang
    - name: Linux Clang
      compiler: clang
    - name: Windows Clang
      os: windows
      install: choco install ninja
      script:
        - cd library
        - ./checkout-eastl.bat
        - ./src/iibmalloc/src/foundation/tools/travis-windows-clang.bat
    - name: Linux GCC (checker)
      compiler: gcc
      cache: ccache
      env:
        - CMAKE_CXX_COMPILER_LAUNCHER=ccache
      script:
        - cd checker
        - ./checkout.sh
        - ./tools/travis-build.sh
    - name: macOS Clang (checker)
      os: osx        
      compiler: clang
      cache: ccache
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - HOMEBREW_NO_INSTALL_CLEANUP=1
        - CMAKE_CXX_COMPILER_LAUNCHER=ccache
      install:
        - brew install ccache
        - brew install sccache
        - brew install ninja
      script:
        - cd checker
        - ./checkout.sh
        - ./tools/travis-build.sh
    - name: Windows MSVC (checker)
      os: windows
      env:
        - CC=cl
        - CXX=cl
        - CMAKE_CXX_COMPILER_LAUNCHER=sccache
      install:
        - choco install ninja
        - choco install sccache --version=0.2.12
      cache:
        directories:
          - $HOME/AppData/Local/Temp/chocolatey
          - $HOME/AppData/Local/Mozilla/sccache
      script:
        - cd checker
        - ./checkout.bat
        - ./tools/travis-windows.bat
    - name: Windows MSVC (sccache-warmup)
      os: windows
      env:
        - CC=cl
        - CXX=cl
        - CMAKE_CXX_COMPILER_LAUNCHER=sccache
      install:
        - choco install ninja
        - choco install sccache --version=0.2.12
      cache:
        directories:
          - $HOME/AppData/Local/Temp/chocolatey
          - $HOME/AppData/Local/Mozilla/sccache
      script:
        - cd checker
        - ./checkout.bat
        - ./tools/travis-windows-sccache-warmup.bat
  allow_failures:        
    - name: macOS Clang
    - name: Windows Clang
    - name: Linux GCC (checker)
    - name: macOS Clang (checker)
    - name: Windows MSVC (checker)
    - name: Windows MSVC (sccache-warmup)
